first commit of italian translation
InnerSourceCommons/InnerSourceLearningPath pull request #310
Opened 2020-09-21 09:25 UTC by OpenPj

This is just a first version of the italian translation.

2020-09-21 14:16 UTC, lenucksi commented
Thanks for contributing this @OpenPj! :tada: 
Since I can't read or write Italian I can't make a judgement on the state of the translation. However, I'm more than happy to merge everything once one (or more) reviewer(s) let me know that it looks good to them. 
Also, I'm happy to help with whatever non-Italian language requiring work is needed.

2020-09-24 15:43 UTC, rrrutledge commented
Amazing!  We've been looking for Italian-speaking reviewers.  @OpenPj, do you know anyone?

2020-09-28 07:11 UTC, dottorblaster commented
@rrrutledge I can do that 🙂

2020-09-28 08:37 UTC, dottorblaster reviewed
Completed an initial proofread of the first three parts, will do the remaining later 😄

2020-09-28 08:37 UTC, dottorblaster commented on introduction/it/02-problems-solved.asciidoc
> +  Comunque, può comportare un importante quantità di sofferenza, specialmente se la funzionalità richiesta non venisse mai espletata.
`un'importante`

2020-09-28 08:37 UTC, dottorblaster commented on introduction/it/02-problems-solved.asciidoc
> +Ioltre, questa opzione non è scalabile in quanto non potrebbe capitare molte volte che un consumatore possa richiedere l'escalation su richieste di funzionalità prima di danneggiare la loro credibili
`Inoltre` instead of `Ioltre` :-) and maybe `non potrebbe capitare` could become `potrebbe non capitare`

2020-09-28 08:37 UTC, dottorblaster commented on introduction/it/02-problems-solved.asciidoc
> +Gli sviluppatori fanno da mentore e imparano gli uni dagli altri condividendo idee e soluzioni in tutti i silos organizzativi.
`Gli sviluppatori fanno da mentori`

2020-09-28 08:37 UTC, dottorblaster commented on introduction/it/03-how-works.asciidoc
> +Il team A sottomette una richiesta di funzionalità al team B, ma il team B non è in grado di implementare quella funzionalità in tempo per il team A.
`sottopone` instead of `sottomette`

2020-09-28 08:37 UTC, dottorblaster commented on introduction/it/03-how-works.asciidoc
> +In un contesto InnerSource, se il team A non può ottenere questa richiesta di funzionalità allora può sottomettere invece una pull request.
`sottoporre`, as above

2020-09-28 08:37 UTC, dottorblaster commented on introduction/it/03-how-works.asciidoc
> +In questo esempio, identifichiamo il team A come _Guest_ team ed il team B come _Host team.
Underscore missing here?

2020-09-28 12:45 UTC, rrrutledge commented
> @rrrutledge I can do that 🙂

Great, @dottorblaster 🙌.  Thank you!

2020-10-02 09:33 UTC, dottorblaster requested changes
Reviewed the remaining parts too :-)

2020-10-02 09:33 UTC, dottorblaster commented on introduction/it/04-benefits.asciidoc
> +InnerSource permette al tempo dell'engineering di fluire organicamente dove le necessità dell'organizzazione lo necessita in un dato momento.
More than `fluire` I'd say `essere spalmato`

2020-10-02 09:33 UTC, dottorblaster commented on introduction/it/05-principles.asciidoc
> +E' fondamentale che questo tutoraggio per i contributori sia _Prioritizzato_ dall'host team.
Is this capital P intentional?

2020-10-02 09:33 UTC, dottorblaster commented on introduction/it/05-principles.asciidoc
> +Mai sarà richiesto ad un guest team di inviare un contribuzione che alla fine non favorisce la loro missione e le loro priorità.
More than `contribuzione` I'd say `contributo`, also look at `un contribuzione`, I think you missed an `a` :D

2020-10-02 09:33 UTC, dottorblaster commented on introduction/it/06-conclusion.asciidoc
> +The commons sponsorizzano un canale Slack, un gruppo di lavoro sui modelli InnerSource, e più summit di persona ogni anno.
`The commons`? 😬

2020-10-02 09:40 UTC, OpenPj commented on introduction/it/05-principles.asciidoc
> +E' fondamentale che questo tutoraggio per i contributori sia _Prioritizzato_ dall'host team.
yep

2020-10-02 09:45 UTC, OpenPj commented on introduction/it/06-conclusion.asciidoc
> +The commons sponsorizzano un canale Slack, un gruppo di lavoro sui modelli InnerSource, e più summit di persona ogni anno.
It should be InnerSource Commons :-P

2020-10-02 10:23 UTC, dottorblaster approved these changes
LGTM!

2020-10-02 10:27 UTC, OpenPj commented
Added all the comments kindly suggested by @dottorblaster :smiley:

2020-10-02 15:51 UTC, rrrutledge commented
Awesome!  Looks like ready to merge?

2020-10-06 07:08 UTC, dottorblaster commented
@rrrutledge I think so, shall we squash the fixup or you'll squash merge?

2020-10-06 09:42 UTC, OpenPj commented
> Awesome! Looks like ready to merge?

Sure, for me ok and please let me know if I have to squash the fixup or you will proceed by yourself as also @dottorblaster asked. Thanks

2020-10-06 13:33 UTC, rrrutledge approved these changes

2020-10-06 13:33 UTC, rrrutledge commented
I will squash merge.

2020-10-06 13:33 UTC, merged