Add first translation, Introduction to the Learning Path
InnerSourceCommons/InnerSourceLearningPath pull request #351
Opened 2020-11-25 18:04 UTC by dicortazar

2020-11-25 18:06 UTC, dicortazar commented
This is a work in progress with the goal of checking if this is the right approach and if you any advise.

Thanks!

2020-11-25 19:41 UTC, lenucksi commented
> 
> 
> This is a work in progress with the goal of checking if this is the right approach and if you any advise.
> 
> Thanks!

Looks good so far as I'm concerned. @tsadler1988 might want to advice on anything we need to look after for our rendering things.
Also, consider adding a bunch of translation strings to #333

2020-11-30 23:25 UTC, rrrutledge commented
Awesome, Daniel!  I myself speak fluent Spanish and so could review, but we'd prefer a native speaker.  Do you know of one in the InnerSource Commons community?  Ideally a non-Bitergian.

2020-12-03 16:17 UTC, tsadler1988 commented
Thanks for this @dicortazar! 

Regarding rendering on the website, you will need to add `es` to the [Introduction translations config](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/scripts/generate_learning_path_markdown.js#L44) as per the [instructions for updating innersourcecommons.org with new articles](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/scripts/generate_learning_path_markdown.js#L44), but this isn't mandatory and could be done separately.

2020-12-16 16:58 UTC, rrrutledge approved these changes

2020-12-17 16:38 UTC, rrrutledge commented on introduction/es/01-introduction-es.asciidoc
> +Además, enumeraremos los principios clave en los que se basa InnerSource y los beneficios que se obtienen cuando se aplica de manera efectiva.
Actually it's not a typo.

2021-02-03 06:49 UTC, rrrutledge requested changes
!Gracias por este trabajo!

2021-02-18 16:21 UTC, dicortazar commented on introduction/es/02-problems-solved-es.asciidoc
> + ..Cualquier tipo de trabajo que realice el equipo que consume el software no va a poder ser reutilizado por otros equipos que necesiten la misma funcionalidad.
Yes, I copied this from the original document format.

Should I use stars as you suggest?

2021-02-18 16:21 UTC, dicortazar commented on introduction/es/02-problems-solved-es.asciidoc
> + ..El equipo consumidor acaba de firmar un contrato no escrito donde van a tener que mantener dicho código en el largo plazo, lo cual no es parte de sus funciones y quizá ni siquiera sea parte de sus
This makes sense, thanks!

2021-02-18 16:28 UTC, dicortazar commented on introduction/es/02-problems-solved-es.asciidoc
> +En el caso de funcionalidades críticas para los equipos que consumen ese software hay generalmente tres opciones, aunque cada una tiene sus propios problemas.
You're right that the very last sentence is not exactly the same as the one in English. I'll reword this a bit :).

2021-02-18 16:34 UTC, dicortazar commented on introduction/es/02-problems-solved-es.asciidoc
> + ..El equipo consumidor acaba de firmar un contrato no escrito donde van a tener que mantener dicho código en el largo plazo, lo cual no es parte de sus funciones y quizá ni siquiera sea parte de sus
Fixed in the new version

2021-02-18 16:34 UTC, dicortazar commented on introduction/es/02-problems-solved-es.asciidoc
> +En el caso de funcionalidades críticas para los equipos que consumen ese software hay generalmente tres opciones, aunque cada una tiene sus propios problemas.
Fixed in the new version

2021-02-19 14:17 UTC, rrrutledge reviewed
Looking really good!  Just one thing I noticed.

2021-02-19 14:17 UTC, rrrutledge commented on introduction/es/02-problems-solved-es.asciidoc
> + ..Cualquier tipo de trabajo que realice el equipo que consume el software no va a poder ser reutilizado por otros equipos que necesiten la misma funcionalidad.
Oh, you're right!  Something's wrong, though. It doesn't render as a list.

<img width="1021" alt="Screen Shot 2021-02-19 at 6 13 40 AM" src="https://user-images.githubusercontent.com/9609562/108515182-a16fcc80-7279-11eb-8ffa-c6ed2b2aa856.png">

Comparing again to the English version, perhaps you need a space between the dots and the text?

```suggestion
 .. Cualquier tipo de trabajo que realice el equipo que consume el software no va a poder ser reutilizado por otros equipos que necesiten la misma funcionalidad.
```

2021-02-21 11:36 UTC, dicortazar commented on introduction/es/02-problems-solved-es.asciidoc
> + ..Cualquier tipo de trabajo que realice el equipo que consume el software no va a poder ser reutilizado por otros equipos que necesiten la misma funcionalidad.
Fixed :)

2021-02-21 11:36 UTC, dicortazar commented
I think we have covered all the suggestions @rrrutledge :). Thanks for all of your comments and pointers.

2021-02-23 18:14 UTC, rrrutledge commented
Looking good!  I will try to get this merged and deployed before our Thursday meeting.

2021-02-25 13:12 UTC, rrrutledge approved these changes

2021-02-25 13:12 UTC, merged