Translation-ja: Add contributor/ja/03-contributor-ethos-article-ja
InnerSourceCommons/InnerSourceLearningPath pull request #356
Opened 2020-12-12 14:07 UTC by ystk

This PR is a part of #339 to add a translation article for 03-contributor-ethos-article.

2020-12-12 19:45 UTC, lenucksi commented
Hey @ystk! Thanks a lot for creating this. 🎉  Happy to merge once I see a LGTM as with the last sections you contributed.

2020-12-15 11:51 UTC, rrrutledge commented
@johtani has lent his review skills in the past.  Is it possible that we can call on you again, Jun?

2020-12-18 10:47 UTC, johtani requested changes
@ystk great translation!
I left some comments, please check it.

2020-12-18 10:47 UTC, johtani commented on contributor/ja/03-contributor-ethos-article-ja.asciidoc
> +あなたが近所を訪問するとき、彼らのアパートであなたを助けてくれるでしょう。彼らは居間への行き方やトイレの場所を教えてくれます。
近所「の人」を訪問するとき、彼らのアパート「の中」で
のほうがわかりやすくなる気がしますがどうでしょう？

2020-12-18 10:47 UTC, johtani commented on contributor/ja/03-contributor-ethos-article-ja.asciidoc
> +これらのファイルには、プロジェクトのチェックアウトしてビルドする方法、テストスイートの実行方法、プロジェクトに変更を提案する方法に関する情報が含まれています。
プロジェクト「を」チェックアウトして...
ではないでしょうか？

2020-12-20 04:57 UTC, ystk commented
@johtani さん、ありがとうございます。
1点ご意見を伺いたいのですが、「ethos」 の訳を「心構え」としていますが、いかがでしょうか？

ethosを単に「エトス」と訳してもうまく伝わらないと思ったので、辞書で意味を調べた上で、「道徳的な慣習」とか「」生活・心理・倫理的態度」のような意味があるので、おおまかな意味をとって「心構え」としました。もうすこし固く言うのであれば、「行動倫理」とか訳すこともできると思います。
章のタイトルなので、わかりやすさを優先すれば良いかなと思うのですが。。。

- [(特定の民族・社会・時代・文化などの)気風、精神](https://ejje.weblio.jp/content/ethos)
- 人間の持続的な性状。また、社会集団における道徳的な慣習
- [生活態度、心的態度、倫理的態度](https://ja.wikipedia.org/wiki/%E3%82%A8%E3%83%BC%E3%83%88%E3%82%B9)

2020-12-20 05:19 UTC, johtani commented
@ystk うまく訳されたタイトルだなと思ったのでそのままでいいのではないでしょうか？それぞれの節のタイトルも固くないので心構えがしっくりくると思います！

2020-12-20 10:02 UTC, ystk commented
@johtani さん、ありがとうございます。レビューで提案いただいた変更点を反映しました。すこし読みやすいように変更しているところもあります。

2020-12-20 16:07 UTC, johtani approved these changes
LGTM!

2021-01-01 13:18 UTC, lenucksi approved these changes
> LGTM

Excellent, thanks for reviewing @johtani and translating @ystk!

2021-01-01 13:18 UTC, merged