Translation-ja: Add contributor/ja/04-mechanics-of-contributing-article
InnerSourceCommons/InnerSourceLearningPath pull request #357
Opened 2021-01-06 10:45 UTC by ystk

This PR adds a translated article in contributor/ja as a part of #339 .

2021-01-08 21:16 UTC, lenucksi commented
Excellent, thank you @ystk! 🎉 As always, happy to merge once I see a LGTM after the review.

2021-01-22 14:09 UTC, rrrutledge commented
Hi @johtani, you've reviewed so many of these translations - do you have time to do this one, also?  We are so excited for them to appear live [on innersourcecommons.org](https://innersourcecommons.org/resources/learningpath/contributor/ja/)!

2021-01-25 08:18 UTC, johtani requested changes
I left some comments.
Please check and fix it :)

2021-01-25 13:14 UTC, ystk commented on contributor/ja/04-mechanics-of-contributing-article-ja.asciidoc
> +* <<_取り組む準備をする,コントリビューションの機会を求め、それに取り組む準備をする>>
日本語の内部参照の挙動が、VSCodeのプレビューと、GitHubのプレビューで異なるので、インラインアンカーをセクションタイトルの前に置いて回避するように変更してみます。ちなみに、

* https://takumon.github.io/asciidoc-syntax-quick-reference-japanese-translation/#_%E5%86%85%E9%83%A8%E7%9B%B8%E4%BA%92%E5%8F%82%E7%85%A7

↑こちらのURLの記事によると、日本語のAsciiDocで内部参照する場合は特殊みたいで、

> 日本語のセクションタイトルの場合、idはタイトル名の冒頭に_を付けたものになります。 内部相互参照は第１引数にid、第２引数に表示名を指定してください。

とのことで、セクションタイトルに_を付けていました。VSCodeでAsciiDocをプレビューすると、想定通りの動作をするのですが、Githubのプレビューでは動かないですね。
逆に、_を外すと、GitHubでは想定通り動くのですが、VSCodeでプレビューすると動作しません。

2021-01-25 13:17 UTC, ystk commented on contributor/ja/04-mechanics-of-contributing-article-ja.asciidoc
> +ホストチームがすでに似たようなものを作っていたり、ソフトウェアを非推奨にしようと計画していたり、あなたが彼らのプロジェクトに適していると提案しようとしているものを見ていない場合に、このようなことが起こる可能性があります。
ありがとうございます！

2021-01-25 13:37 UTC, ystk commented
Hi @johtani san,
Thanks for your comments. I update the file to include your suggestions and fixes.

2021-01-25 16:10 UTC, johtani commented on contributor/ja/04-mechanics-of-contributing-article-ja.asciidoc
> +* <<_取り組む準備をする,コントリビューションの機会を求め、それに取り組む準備をする>>
なるほど。じゃあ、`_`があったほうがいいのかもしれないですねぇ。こればっかりはビルドしないとわからないですね。

2021-01-25 16:13 UTC, johtani commented on contributor/ja/04-mechanics-of-contributing-article-ja.asciidoc
> +オープンソースの領域では何度も証明されているように、もしあなたの提案を議論する方法を選択できるとしたら、文書による方法を選択肢してみるべきです。
「選択肢」の「肢」が残っているみたいです。

2021-01-25 16:14 UTC, johtani commented
Basically LGTM! I left a comment.

2021-01-26 13:39 UTC, ystk commented
Oops! I messed up... I updated it again. Please check it.

2021-01-26 14:14 UTC, johtani approved these changes
LGTM!

2021-01-28 16:41 UTC, rrrutledge approved these changes

2021-01-28 16:41 UTC, rrrutledge commented
Amazing!

2021-01-28 16:41 UTC, merged