Translation-ja: Add contributor/ja/05-benefits and 06-conclusion
InnerSourceCommons/InnerSourceLearningPath pull request #360
Opened 2021-01-12 15:13 UTC by ystk

This PR relates to issue #339 .

2021-01-28 16:29 UTC, johtani requested changes
@ystk I left only two comments.
Please check and fix :)

2021-01-28 16:44 UTC, rrrutledge commented
Thank you so much for reviewing, @johtani.  You are a ⭐ ❗

2021-01-30 04:54 UTC, ystk commented on contributor/ja/05-benefits-of-contribution-article-ja.asciidoc
> +一般的に、 https://en.wikipedia.org/wiki/Bus_factor[バスファクター] が1人か2人のプロジェクトが組織にリスクをもたらすことがよく理解いますが、そのプロジェクトがビジネスの目的の中心であることが明らかになった場合はなおさらです。
ありがとうございます！
この文、よくみると「が」も多いと思ったので、一箇所「は」に変更してみます。
「組織にリスクをもたらすことが」→「組織にリスクをもたらすことは」

2021-01-30 05:02 UTC, ystk commented
Thanks a lot, @johtani . I updated the files and added minor fixes. Please check it.

2021-01-30 08:23 UTC, johtani approved these changes
LGTM!

2021-02-02 15:07 UTC, rrrutledge approved these changes

2021-02-02 15:07 UTC, merged