Translation-ja: Add trusted-committer/ja/02-ensuring-product-quality
InnerSourceCommons/InnerSourceLearningPath pull request #371
Opened 2021-02-20 06:19 UTC by ystk

This is the second PR for #367 .

2021-02-23 13:31 UTC, johtani requested changes
@ystk, I left a comment.
Please review it.

2021-02-23 13:31 UTC, johtani commented on trusted-committer/ja/02-ensuring-product-quality-ja.asciidoc
> +Trusted Committerは、これらの発見が捕捉されドキュメント化されたことを https://innersourcecommons.org/resources/learningpath/product-owner/index[_プロダクトオーナー_] と https://innersourcecommons.org/resources/learningpath/contributor/
「これらの発見をプロダクトオーナーとコントリビューターのために捕捉し、ドキュメントにすることを確認する責任もあります。」のほうがしっくりくるかなと。どうでしょう？

2021-02-23 18:26 UTC, rrrutledge commented
@johtani thank you so much for this review!  You've been so reliable and helpful for reviewing this text.  We are very grateful.  I would really like to make sure that you are recognized for your work and service on our website.  We have a contributors list that is auto-generated off of the list of committers to the file.  I believe that if you leave a piece of feedback as a "commit suggestion" that is then accepted by Yoshi then your name will show up in the commit history and on the website.  If you ever have any feedback that could be given as a commit suggestion then place do so that you can show up with the credit that you've earned through your service.

2021-02-24 10:01 UTC, johtani commented
@rrrutledge thank you for your comment. I haven't known "commit suggestion"! I'll do that next time :)

2021-02-25 10:41 UTC, ystk commented on trusted-committer/ja/02-ensuring-product-quality-ja.asciidoc
> +Trusted Committerは、これらの発見が捕捉されドキュメント化されたことを https://innersourcecommons.org/resources/learningpath/product-owner/index[_プロダクトオーナー_] と https://innersourcecommons.org/resources/learningpath/contributor/
ありがとうございます。

2021-02-25 10:43 UTC, ystk commented
Thanks for the review, @johtani . Please check it, again.

2021-02-25 14:24 UTC, johtani approved these changes
LGTM!

2021-02-25 16:42 UTC, merged