Translation-ja: Add trusted-committer/ja/03-keeping-the-community-healthy
InnerSourceCommons/InnerSourceLearningPath pull request #379
Opened 2021-03-09 13:01 UTC by ystk

This is the third PR for #367 .

2021-03-09 16:40 UTC, johtani requested changes
Hi @ystk , great work!
I left 3 suggestions, please check these.

2021-03-09 16:40 UTC, johtani commented on trusted-committer/ja/03-keeping-the-community-healthy-ja.asciidoc
> +最後に、InnerSource のコミュニティに留まる人たちもいますが、それは彼らがオーバーヘッドや無駄と考えられる活動の代わりにソフトウェアの開発に集中するようになったからで、これはプロセスに重点を置いている大企業では特によく見られるものです。
```suggestion
最後に、特にプロセスに重点を置いている大企業で、彼らがオーバーヘッドや無駄と考える活動の代わりに、ソフトウェアの開発に集中できるのでInnerSource のコミュニティに留まる人たちもいます。
```
ではどうでしょう？

2021-03-09 16:40 UTC, johtani commented on trusted-committer/ja/03-keeping-the-community-healthy-ja.asciidoc
> +一般的に、Trusted Committer はコントリビューションプロセスがより多くの問題を作らないことを確認する必要がありますが、それよりも問題の特定と解決でコミュニティをサポートします。
```suggestion
一般的に、Trusted Committer は、コントリビューションプロセスがより多くの問題を作らず、それよりも問題の特定と解決でコミュニティをサポートすることを確認する必要があります。
```
はどうでしょう？

2021-03-09 17:19 UTC, rrrutledge commented
Awesome, @johtani❗  And since you are doing commit suggestions your name will show up on the website as a contributor!

2021-03-10 05:09 UTC, ystk commented
Thanks for suggestions, @johtani ! I merged your suggested changes.

2021-03-10 05:48 UTC, johtani approved these changes
LGTM!

2021-03-10 16:10 UTC, merged

2021-03-10 16:12 UTC, rrrutledge commented
Great work, both.  We'll get it on the website.

2021-03-11 00:57 UTC, rrrutledge commented
Opened pull request for the website: https://github.com/InnerSourceCommons/innersourcecommons.org/pull/258.  Both of your names listed as contributing!