Translation-ja: Add trusted-committer/ja/05-lowering-the-barriers-to-entry
InnerSourceCommons/InnerSourceLearningPath pull request #401
Opened 2021-05-12 14:15 UTC by ystk

This PR is a part of #367 .

2021-05-12 15:35 UTC, johtani requested changes
Great work, @ystk 
I left some comments. Please check my comments!

2021-05-12 15:35 UTC, johtani commented on trusted-committer/ja/05-lowering-the-barriers-to-entry-ja.asciidoc
> +さらに、リポジトリ内のソフトウェアの取得、構築、テスト、および使用方法について、ライセンスに関する情報も含めて詳細な手順を提供する必要があります。
```suggestion
さらに、ライセンスに関する情報も含め、リポジトリ内のソフトウェアの取得、構築、テスト、および使用方法について詳細な手順を提供する必要があります。
```
ライセンスは手順ではないので少し違和感がありました。

2021-05-12 15:35 UTC, johtani commented on trusted-committer/ja/05-lowering-the-barriers-to-entry-ja.asciidoc
> +** コントリビューションが受け入れられた後に、コントリビューションしたコードに対するサポートには何が期待されるか。
```suggestion
** コントリビューションが受け入れられた後に、コントリビューションしたコードに対するサポートとして、何を期待しているか。
```

2021-05-12 15:35 UTC, johtani commented on trusted-committer/ja/05-lowering-the-barriers-to-entry-ja.asciidoc
> +これら文書化の作業に加えて、オープンソースソフトウェアの開発と同様に、潜在的な https://innersourcecommons.org/resources/learningpath/contributor/index[_コントリビューター_] によってローカルに開発されるソフトウェアの実行とテストが簡単かつ直ぐに行えるようにすべきで、それにより可能な限り少ない労力でコントリビューションの実
```suggestion
これら文書化の作業に加えて、オープンソースソフトウェアの開発と同様に、潜在的な https://innersourcecommons.org/resources/learningpath/contributor/index[_コントリビューター_] によってローカルに開発されるソフトウェアの実行とテストが簡単かつ直ぐに行えるようにすべきです。
それにより可能な限り少ない労力でコントリビューションの実装と検証を開始することができます。
```
長いので2つの文章にするとわかりやすいかと。

2021-05-12 15:35 UTC, johtani commented on trusted-committer/ja/05-lowering-the-barriers-to-entry-ja.asciidoc
> +
```suggestion
```
元の文章は1つの節のため

2021-05-12 15:35 UTC, johtani commented on trusted-committer/ja/05-lowering-the-barriers-to-entry-ja.asciidoc
> +したがって、どのようなInnerSourceコミュニティでも、このような質問に回答するコンタクトパーソンが1人以上いることが重要となります。
```suggestion
したがって、どのようなInnerSourceコミュニティでも、このような質問に回答する担当者が1人以上いることが重要となります。
```

2021-05-12 15:35 UTC, johtani commented on trusted-committer/ja/05-lowering-the-barriers-to-entry-ja.asciidoc
> +通常はTrusted Committerのグループの誰かがコンタクトパーソンになりますが、そうでなければ「オンコール」のコミュニティメンバーがいることを確認する必要があります。
```suggestion
通常はTrusted Committerのグループの誰かが担当者になりますが、そうでなければ「オンコール」のコミュニティメンバーがいることを確認する必要があります。
```

2021-05-13 00:09 UTC, rrrutledge commented
Very fast feedback.  Great work, both!

2021-05-13 04:14 UTC, ystk commented
Thanks for the suggestions, @johtani . I applied all suggested changes.

2021-05-13 04:21 UTC, johtani approved these changes
LGTM!

2021-05-13 11:51 UTC, lenucksi commented
Thanks for the contribution and the reviews @ystk and @johtani! :tada:  I'm merging this then.

2021-05-13 11:51 UTC, merged

2021-05-13 13:49 UTC, rrrutledge commented
Great!  Opened a [pull request](https://github.com/InnerSourceCommons/innersourcecommons.org/pull/122) to get it on the website.