Translation-ja: Add product-owner/ja/01-opening-article
InnerSourceCommons/InnerSourceLearningPath pull request #408
Opened 2021-05-29 06:32 UTC by ystk

This is Japanese translation of the first article in Product Owner chapter which relate to #407 .

2021-05-29 13:42 UTC, johtani commented on product-owner/ja/01-opening-article-ja.asciidoc
> +
```suggestion
```
No need new line.

2021-05-29 13:46 UTC, johtani commented on product-owner/ja/01-opening-article-ja.asciidoc
> +InnerSourceプロセスを通じて、私達は数十年積み残していた内部残件を1年足らずで削減もしました。
```suggestion
InnerSourceプロセスを通じて、私たちは数十年積み残していた内部残件を1年足らずで削減もしました。
```

2021-05-29 13:51 UTC, johtani requested changes
Great @ystk !
I left some comments and suggestions,
Please check it.

2021-05-29 13:51 UTC, johtani commented on product-owner/ja/01-opening-article-ja.asciidoc
> +これは、ほとんどの企業のチームが閉じ込められているサイロを破壊します。
```suggestion
これは、ほとんどの企業のチームが陥っているサイロ化を破壊します。
```

2021-05-30 11:00 UTC, ystk commented
Thanks for your review, @johtani ! I applied all your suggestions.

2021-05-30 12:09 UTC, johtani approved these changes
LGTM! Thanks, @ystk

2021-06-10 15:35 UTC, merged

2021-06-10 15:35 UTC, rrrutledge commented
Great work, all!