Adds a machine translation of the introduction articles and index.md to French using DeepL
InnerSourceCommons/InnerSourceLearningPath pull request #414
Opened 2021-06-10 17:25 UTC by lenucksi

This pull request adds a machine translated version of the introduction section, including the index.ml to French using the DeepL machine translator.

Let's review this for quality if machine translation to french is feasible. Also, we might want to take a look if we can take the free translation service for this or would need to give any attribution to it etc - as well as to the human reviewers obviously.

2021-06-12 09:21 UTC, SJVle commented
Hi, how I can read the results of the Deepl translation, I dont see it...

2021-06-13 10:56 UTC, SJVle commented on introduction/fr/04-avantages.asciidoc
> +InnerSource offre à une entreprise une stratégie évolutive permettant aux *équipes invitées d'obtenir des demandes de fonctionnalités lorsqu'elles en ont besoin*, sans le fardeau à long terme de la m
L'InnerSource offre à une entreprise une stratégie évolutive permettant aux *équipes invitées d'obtenir des demandes de fonctionnalités lorsqu'elles en ont besoin*, sans le fardeau à long terme de la maintenance.

2021-06-13 10:56 UTC, SJVle commented on introduction/fr/04-avantages.asciidoc
> +Bien que ce résultat soit un avantage indéniable d'InnerSource, il existe de nombreux avantages pour les hôtes qui reçoivent régulièrement des contributions d'InnerSource.
Bien que ce résultat soit un avantage indéniable de l'InnerSource, il existe de nombreux avantages pour les hôtes qui reçoivent régulièrement des contributions via l'InnerSource.

2021-06-13 10:56 UTC, SJVle commented on introduction/fr/04-avantages.asciidoc
> +Rappelez-vous que, dans le cadre du processus d'InnerSource, le propriétaire du produit de l'équipe hôte convient dès le départ que les fonctions contribuées sont bonnes et souhaitables.
Rappelez-vous que, dans le cadre du processus de l'InnerSource, le propriétaire du produit de l'équipe hôte convient dès le départ que les fonctions issues des contributions sont bonnes et souhaitables.

2021-06-13 10:56 UTC, SJVle commented on introduction/fr/04-avantages.asciidoc
> +*InnerSource fournit à l'équipe hôte une stratégie évolutive* pour répondre à des quantités variables de fonctionnalités demandées par ses nombreux clients.
*L'InnerSource fournit à l'équipe hôte une stratégie évolutive* pour répondre à des quantités variables de fonctionnalités demandées par ses nombreux clients.

2021-06-13 10:56 UTC, SJVle commented on introduction/fr/04-avantages.asciidoc
> +Sans InnerSource, cette situation peut facilement conduire à une équipe stressée et surchargée de travail qui doit faire face à de nombreuses demandes de fonctionnalités transmises à ses dirigeants.
Sans l'InnerSource, cette situation peut facilement conduire une équipe à être stressée et surchargée de travail et qui doit faire face aux nombreuses demandes de fonctionnalités transmises vers ses dirigeants.

2021-06-13 10:56 UTC, SJVle commented on introduction/fr/04-avantages.asciidoc
> +Cependant, si l'équipe hôte fonctionne via InnerSource, les ressources d'ingénierie nécessaires pour construire ces fonctionnalités apparaîtront proportionnellement à leur importance sous la forme de
Cependant, si l'équipe hôte fonctionne via l'InnerSource, les ressources d'ingénierie nécessaires pour construire ces fonctionnalités apparaîtront proportionnellement à leur importance sous la forme de contributeurs invités.

2021-06-13 10:56 UTC, SJVle commented on introduction/fr/04-avantages.asciidoc
> +*InnerSource devient un multiplicateur de force* qui permet à l'équipe hôte d'agir temporairement plus que sa taille réelle pendant les périodes de forte demande.
*L'InnerSource devient un multiplicateur de ressources* qui permet à l'équipe hôte d'agir temporairement plus que sa taille réelle pendant les périodes de forte demande.

2021-06-13 10:56 UTC, SJVle commented on introduction/fr/04-avantages.asciidoc
> +InnerSource permet au temps d'ingénierie de circuler organiquement là où l'organisation en a besoin à un moment donné.
L'InnerSource permet au temps d'ingénierie de circuler organiquement là où l'organisation en a besoin à un moment donné.

2021-06-13 10:56 UTC, SJVle commented on introduction/fr/04-avantages.asciidoc
> +Au-delà du travail brut que l'équipe hôte est capable d'accomplir dans son système, les contributions régulières d'InnerSource donnent à l'équipe hôte *un meilleur alignement des exigences et des pri
Au-delà du travail brut que l'équipe hôte est capable d'accomplir dans son système, les contributions régulières via l'InnerSource donnent à l'équipe hôte *un meilleur alignement des exigences et des priorités avec tous ses consommateurs*.

2021-06-13 10:56 UTC, SJVle commented on introduction/fr/04-avantages.asciidoc
> +Une équipe hôte peut faire sa meilleure collecte d'exigences sur le travail qu'elle produit, mais lorsque le consommateur lui-même est celui qui soumet le travail, les chances sont beaucoup plus gran
Une équipe hôte peut faire une meilleure collecte d'exigences sur le travail qu'elle produit, mais lorsque le consommateur lui-même est celui qui soumet le travail, les chances sont beaucoup plus grandes que le changement résultant soit aligné sur ce dont le consommateur a besoin.

2021-06-13 10:56 UTC, SJVle commented on introduction/fr/04-avantages.asciidoc
> +En plus de cet alignement, il y a également une formation générale et une éducation de https://innersourcecommons.org/learn/learning-path/contributor/01 [contributeurs] car ils travaillent avec et ap
En plus de cet alignement, il y a également une formation générale et une éducation des https://innersourcecommons.org/learn/learning-path/contributor/01 [contributeurs] car ils travaillent avec et apprennent du https://innersourcecommons.org/learn/learning-path/trusted-committer/01 [committers de confiance].

2021-06-13 10:56 UTC, SJVle commented on introduction/fr/05-principles.asciidoc
> +== Principes d'InnerSource
== Les principes de l'InnerSource

2021-06-13 10:56 UTC, SJVle commented on introduction/fr/05-principles.asciidoc
> +Ces principes ont été inspirés par des projets open source réussis et sont nécessaires pour qu'InnerSource obtienne les avantages décrits précédemment.
Ces principes ont été inspirés de projets open source réussis et sont nécessaires pour que l'InnerSource obtienne les avantages décrits précédemment.

2021-06-13 10:56 UTC, SJVle commented on introduction/fr/05-principles.asciidoc
> +*Openness* (Ouverture)
*L'ouverture* (Openness)

2021-06-13 10:56 UTC, SJVle commented on introduction/fr/05-principles.asciidoc
> +*Transparence
*La transparence

2021-06-13 10:56 UTC, SJVle commented on introduction/fr/05-principles.asciidoc
> +* Mentorat prioritaire
Un Mentorat prioritaire

2021-06-13 10:56 UTC, SJVle commented on introduction/fr/05-principles.asciidoc
> +*Contribution volontaire au code*.
*La Contribution volontaire au code*

2021-06-13 10:56 UTC, SJVle commented on introduction/fr/06-conclusion.asciidoc
> +Un projet InnerSource réussi implique un https://innersourcecommons.org/learn/learning-path/product-owner/01[_product owner_] et un https://innersourcecommons.org/learn/learning-path/trusted-committe
Un projet InnerSource réussi implique un https://innersourcecommons.org/learn/learning-path/product-owner/01[_product owner_] et un https://innersourcecommons.org/learn/learning-path/trusted-committer/01[_trusted committer_] de l'équipe *hôte* ainsi qu'un https://innersourcecommons.org/learn/learning-path/contributor/01[_contributor_] de l'équipe *invitée*.

2021-06-13 10:56 UTC, SJVle commented on introduction/fr/06-conclusion.asciidoc
> +Réalisée efficacement, InnerSource apporte de nombreux avantages aux deux équipes participantes.
Réalisée efficacement, l'InnerSource apporte de nombreux avantages aux deux équipes participantes.

2021-06-13 10:56 UTC, SJVle commented on introduction/fr/06-conclusion.asciidoc
> +Bien que cette formation donne un aperçu de haut niveau d'InnerSource, il existe de nombreux autres détails utiles pour faire fonctionner InnerSource pour votre équipe.
Bien que cette formation donne un aperçu de haut niveau de l'InnerSource, il existe de nombreux autres détails utiles pour faire fonctionner l'InnerSource pour votre équipe.

2021-06-13 10:56 UTC, SJVle commented on introduction/fr/06-conclusion.asciidoc
> +Si vous souhaitez rester connecté à la conversation en cours autour d'InnerSource et de ses meilleures pratiques, alors rejoignez http://innersourcecommons.org [the InnerSource Commons].
Si vous souhaitez rester connecté à la conversation en cours autour de l'InnerSource et de ses meilleures pratiques, alors rejoignez http://innersourcecommons.org [the InnerSource Commons].

2021-06-13 10:56 UTC, SJVle commented on introduction/fr/06-conclusion.asciidoc
> +Le commons sponsorise un canal Slack, un groupe de travail sur les modèles InnerSource, et plusieurs sommets en personne chaque année.
L'Innersource commons sponsorise un canal Slack, un groupe de travail sur les modèles InnerSource, et plusieurs rencontres en physique chaque année.

2021-06-13 10:56 UTC, SJVle commented on introduction/fr/06-conclusion.asciidoc
> +La participation au commons est un excellent moyen de rester connecté avec les dernières nouveautés d'InnerSource.
La participation au groupe Innnersource commons est un excellent moyen de rester connecté avec les dernières nouveautés de l'InnerSource.

2021-06-14 10:21 UTC, lenucksi reviewed
I've turned your review comments into [commit suggestions](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request) such that they are directly incorporated into the text. 

There was one where I wasn't 100% sure if the edit was correct, please take a look there.

2021-06-14 10:21 UTC, lenucksi commented on introduction/fr/02-problèmes-résolus.asciidoc
> +. *Attendre. L'équipe utilisatrice peut ne rien faire et rester sans la fonctionnalité demandée.
Changed this into a commit suggestion (as with the others). However the match was not perfectly clear. Is that the desired one?

2021-06-14 13:10 UTC, SJVle commented on introduction/fr/04-avantages.asciidoc
>  == Quels sont les avantages d'InnerSource ?
== Quels sont les avantages de l'InnerSource ?

2021-06-14 13:10 UTC, SJVle commented on introduction/fr/04-avantages.asciidoc
>  InnerSource permet à l'équipe hôte de recevoir *une aide pour créer un meilleur produit* pour ses consommateurs !
L'InnerSource permet à l'équipe hôte de recevoir *une aide pour créer un meilleur produit* pour ses consommateurs.

2021-06-14 13:10 UTC, SJVle commented on introduction/fr/06-conclusion.asciidoc
>  Dans ce parcours d'apprentissage, nous avons donné une introduction à InnerSource.
Dans ce parcours d'apprentissage, nous avons proposé une introduction à l'InnerSource.

2021-06-14 13:10 UTC, SJVle commented on introduction/fr/06-conclusion.asciidoc
>  InnerSource applique les meilleures pratiques et les principes de l'open source au développement de logiciels internes.
L'InnerSource applique les meilleures pratiques et les principes de l'open source au développement de logiciels internes.

2021-06-14 18:44 UTC, SJVle commented on introduction/fr/01-introduction.asciidoc
> +InnerSource est l'application des pratiques et principes de l'open source au développement de logiciels au sein de l'entreprise.
L'InnerSource est l'application des pratiques et principes de l'open source au développement de logiciels au sein de l'entreprise.

2021-06-14 18:44 UTC, SJVle commented on introduction/fr/01-introduction.asciidoc
> +Ce parcours d'apprentissage enseigne comment reconnaître les situations qui sont de bons candidats pour InnerSource.
Ce parcours d'apprentissage vous apprend comment reconnaître les situations qui sont de bonnes candidates pour l'InnerSource.

2021-06-14 18:44 UTC, SJVle commented on introduction/fr/01-introduction.asciidoc
> +Nous décrirons à un haut niveau comment InnerSource peut aider dans ces situations.
Nous décrirons à un haut niveau comment l'InnerSource peut aider dans ces situations.

2021-06-15 12:36 UTC, SJVle requested changes

2021-06-15 12:36 UTC, SJVle commented on introduction/fr/01-introduction.asciidoc
> +L'innerSource est la mise en oeuvre des pratiques et des principes de l'Open Source du développement logiciel au sein de l'entreprise.
L'InnerSource est la mise en oeuvre des pratiques et des principes du développement logiciel de l'Open Source au sein de l'entreprise.

2021-06-15 12:36 UTC, SJVle commented on introduction/fr/01-introduction.asciidoc
> +Ce parcours d'apprentissage enseigne comment reconnaître les situations qui sont de bonnes candidates pour l'InnerSource.
Ce parcours d'apprentissage apprend à reconnaître les situations qui sont de bonnes candidates pour l'InnerSource.

2021-06-15 12:47 UTC, SJVle requested changes

2021-06-15 12:47 UTC, SJVle commented on introduction/fr/02-problèmes-résolus.asciidoc
> +Cette discussion ouvre la voie à InnerSource.
Cette discussion ouvre la voie à l'InnerSource.

2021-06-15 13:24 UTC, SJVle requested changes

2021-06-15 13:24 UTC, SJVle commented on introduction/fr/03-comment fonctionne.asciidoc
> +Ils peuvent espérer ou attendre une invitation de retour, à condition d'avoir été courtois et polis.
Ils peuvent espérer ou attendre une invitation en retour, à condition d'avoir été courtois et polis.

2021-06-15 13:24 UTC, SJVle commented on introduction/fr/03-comment fonctionne.asciidoc
> +Ces concepts relatifs à la visite d'une maison sont une métaphore de l'attitude et des comportements que les équipes doivent adopter lorsqu'elles accueillent une autre personne qui contribue à la bas
Ces concepts relatifs à la visite d'une maison sont une métaphore de l'attitude et des comportements que les équipes doivent adopter lorsqu'elles accueillent une autre personne qui contribue à la base du code.

2021-06-15 13:24 UTC, SJVle commented on introduction/fr/03-comment fonctionne.asciidoc
> +Dans le cas de petits projets de base, une seule personne remplit souvent les rôles de propriétaire du produit et de commiteur de confiance (Trusted comitter).
Dans le cas de petits projets de base, une seule personne remplit souvent les rôles de propriétaire du produit et de committeur de confiance (Trusted committer).

2021-06-15 13:24 UTC, SJVle commented on introduction/fr/03-comment fonctionne.asciidoc
> +* Le propriétaire du produit s'assure que les histoires d'utilisateur (Users Stories) représentant la demande de fonctionnalité sont créées, soit par les membres de l'équipe invitée, soit par l'équip
* Le propriétaire du produit s'assure que les histoires d'utilisateur (Users Stories) représentant la demande de fonctionnalité sont créées, soit par les membres de l'équipe invitée, soit par l'équipe hôte.

2021-06-15 13:24 UTC, SJVle commented on introduction/fr/03-comment fonctionne.asciidoc
> +Ils énumèrent également tous les détails fournis par l'équipe hôte sur la manière dont la fonctionnalité doit être fournie pour que le travail soit accepté.
Ils listent également tous les détails fournis par l'équipe hôte sur la manière dont la fonctionnalité devrait être livrée pour que le travail soit accepté.

2021-06-15 13:24 UTC, SJVle commented on introduction/fr/03-comment fonctionne.asciidoc
> +* Soutenu par le commiter de confiance, le contributeur soumet la demande de modification pour implémenter la fonctionnalité demandée.
Soutenu par le committer de confiance, le contributeur soumet la demande d'évolution pour implémenter la fonctionnalité demandée.

2021-06-15 16:31 UTC, SJVle requested changes

2021-06-16 09:40 UTC, SJVle requested changes

2021-06-16 09:40 UTC, SJVle commented on introduction/fr/05-principles.asciidoc
> +Ce mentorat est précieux à la fois pour le contributeur individuel et pour l'hôte, et il vaut la peine de bien le faire.
Ce mentorat est précieux à la fois pour le contributeur individuel et pour l'hôte, et ça vaut la peine de bien le faire.

2021-06-16 09:40 UTC, SJVle commented on introduction/fr/05-principles.asciidoc
> +Il s'avère mutuellement bénéfique à long terme. En améliorant le code, le contributeur noue ou améliore des relations au sein d'une organisation qui n'aurait peut-être pas pu le faire.
Il s'avère mutuellement bénéfique à long terme. En améliorant le code, le contributeur noue ou améliore des relations, au sein d'une organisation, qui n'auraient peut-être pas existées autrement.

2021-06-16 09:40 UTC, SJVle commented on introduction/fr/05-principles.asciidoc
> +améliore des relations au sein d'une organisation qui n'auraient peut-être pas existé autrement.
(bis repetita) to delete "améliore des relations au sein d'une organisation qui n'auraient peut-être pas existé autrement."

2021-06-16 09:40 UTC, SJVle commented on introduction/fr/05-principles.asciidoc
> +=== Contribution volontaire au code
=== La contribution volontaire au code

2021-06-16 09:40 UTC, SJVle commented on introduction/fr/05-principles.asciidoc
> +Le premier mot _Volontaire_ signifie que l'engagement dans InnerSource des équipes invitées et hôtes se fait de leur plein gré.
Le mot _Volontaire_ signifie que l'engagement dans l'InnerSource des équipes invitées et hôtes se fait de leur plein gré.

2021-06-16 09:40 UTC, SJVle commented on introduction/fr/05-principles.asciidoc
> +Cette nature volontaire signifie que chaque équipe doit être certaine que sa participation apporte une valeur ajoutée aux objectifs des autres.
Cette inscription de l'équipe dans un aspect volontaire signifie que chaque équipe doit être certaine que son implication apporte de la valeur ajoutée aux objectifs des autres.

2021-06-16 09:40 UTC, SJVle commented on introduction/fr/05-principles.asciidoc
> +La participation des invités à l'ouverture des problèmes, à la mise à jour des exigences, à la correction des documents, etc. est une bonne chose, mais la collaboration doit aller jusqu'à la soumissi
L'implication des invités dans l'ouverture des problèmes, la mise à jour des exigences, la correction des documents, etc. est une bonne chose, mais la collaboration doit aller jusqu'à la soumission de code pour obtenir tous les avantages dont nous avons parlé.

2021-06-16 12:53 UTC, SJVle requested changes

2021-06-16 22:06 UTC, SJVle commented
Let's merge and then we will see. Iteration is the matter.

2021-06-17 11:12 UTC, lenucksi commented
> Let's merge and then we will see. Iteration is the matter.

I've converted everything applicable (i.e. not outdated) to a commit suggestion and applied it. Merging and iterating sounds good. We can always add more pull requests to the files.

2021-06-17 11:12 UTC, merged