Revert "Translation-ja: Add product-owner/ja/03-major-benefits"
InnerSourceCommons/InnerSourceLearningPath pull request #422
Opened 2021-06-17 13:04 UTC by ystk

Reverts InnerSourceCommons/InnerSourceLearningPath#416

The original PR was merged without review. The purpose of this revert PR is for review.

2021-06-17 13:09 UTC, ystk commented
As @rrrutledge mentioned in #416 , I revier #416 first. Then added same document for review. 
Please use this PR, @johtani .

2021-06-18 07:08 UTC, johtani requested changes
Thanks @ystk for making new PR.
I left a comment, please take a look.

2021-06-18 09:13 UTC, ystk commented on product-owner/ja/03-major-benefits-are-built-into-the-innersource-process-article-ja.asciidoc
> +しかし、上級管理職が、あなたが経験しているさまざまな道筋や、プロジェクトの過去と今後に関してあなたが何をしているかを見ることができるという信用の側面もあります。
Thanks a lot for your review, @johtani . I make a change to apply your suggestion. 

I am not sure why that label shows Outdated. Maybe I made a mistake..

2021-06-18 09:48 UTC, johtani approved these changes
LGTM!

2021-06-18 14:48 UTC, merged