Translation-ja: Add product-owner/ja/06-closing-and-contact
InnerSourceCommons/InnerSourceLearningPath pull request #425
Opened 2021-06-20 01:56 UTC by ystk

This PR is a part of #407 . Also, this is the final PR for Japanese translations for the main articles in all segments. :)

2021-06-20 15:04 UTC, johtani requested changes
@ystk I left a suggestion, please take a look.

2021-06-20 15:04 UTC, johtani commented on product-owner/ja/06-closing-and-contact-article-ja.asciidoc
> +また、Trusted Committerなどの役割や、あなたの最初のコントリビューションの合意形成のような、いくつかの文書についても説明しています。
```suggestion
また、https://innersourcecommons.org/learn/learning-path/trusted-committer/01[Trusted Committer] などの役割や、あなたの最初のコントリビューションの合意形成のような、いくつかの文書についても説明しています。
```

2021-06-20 23:42 UTC, ystk commented on product-owner/ja/06-closing-and-contact-article-ja.asciidoc
> +また、Trusted Committerなどの役割や、あなたの最初のコントリビューションの合意形成のような、いくつかの文書についても説明しています。
Thanks for fixing this.

2021-06-20 23:43 UTC, ystk commented
I merged your suggested change. Thank you, @johtani .

2021-07-03 11:06 UTC, ystk commented
Hi @johtani ,
When you have a time, please review this PR.

2021-07-05 01:29 UTC, johtani approved these changes
LGTM!

2021-07-05 07:29 UTC, lenucksi approved these changes
Thanks for creating this @ystk and the review @johtani! :tada: :rocket:

2021-07-05 07:29 UTC, merged

2021-07-05 12:08 UTC, rrrutledge commented
Nice work, everyone!