Change of publishing path due to i18n support for innersourcecommons.org page
InnerSourceCommons/InnerSourceLearningPath pull request #515
Opened 2022-11-28 16:04 UTC by yuhattor

To support i18n at innersourcecommons.org, LearningPath also needs to be partially changed.
This change should or should not be merged depending on the success or failure of the following changes

@rrrutledge, could you check the following PR?
https://github.com/InnerSourceCommons/innersourcecommons.org/pull/412

2022-11-28 18:27 UTC, rrrutledge requested changes
Thanks for this work, @yuhattor ❗  So amazing.  Can you incorporate these suggestions as well?  https://github.com/isc-i18n/InnerSourceLearningPath/pull/1

2022-11-29 15:11 UTC, yuhattor commented
Merged!

2022-11-29 17:02 UTC, rrrutledge approved these changes
Looks great!  Is there a ordering between when this one should be merged (vs. the PR to the innersourcecommons.org repo)?

2022-11-30 13:55 UTC, yuhattor commented
Thanks! Yes, it should be merged after the PR #412 is merged👍
I will ask you for the approval then

2022-11-30 14:48 UTC, rrrutledge commented
Sounds great, @yuhattor .  Thanks for working on this.

2022-12-02 11:24 UTC, yuhattor commented
@rrrutledge 
As the PR was merged, could you merge this PR?

2022-12-02 12:14 UTC, merged

2022-12-02 13:10 UTC, yuhattor commented
Thank you!