Publish Project Leader Section
InnerSourceCommons/InnerSourceLearningPath pull request #561
Opened 2023-05-25 22:30 UTC by rrrutledge

Update deployment script to pick up on added files (not just modified files).

2023-05-29 14:48 UTC, rrrutledge commented
Maybe @lenucksi can take a look?

2023-05-30 15:13 UTC, tsadler1988 requested changes

2023-05-30 15:13 UTC, tsadler1988 commented on .github/workflows/publish-to-website.yml
> +          git add . && git commit -m "Update Learning Path articles" && git push
```suggestion
          git add .
          git diff --staged --quiet || (git commit -m "Update Learning Path articles" && git push)
```
This should pick up new files whilst also preventing the CI failing if there are no changes to push.

2023-05-30 15:35 UTC, tsadler1988 approved these changes

2023-05-30 15:36 UTC, merged